//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkhausManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public bool Event { get; set; }
        public Nullable<System.DateTime> Zeit { get; set; }
        public int ParkplatzNummer { get; set; }
        public bool Typ { get; set; }
        public Nullable<int> Dauermieter_Id { get; set; }
        public int Stockwerk_Id { get; set; }
    
        public virtual Dauermieter Dauermieter { get; set; }
        public virtual Stockwerk Stockwerk { get; set; }
    }
}
