//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkhausManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stockwerk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stockwerk()
        {
            this.Dauermieter = new HashSet<Dauermieter>();
            this.Ticket = new HashSet<Ticket>();
            this.Log = new HashSet<Log>();
            this.Zahlung = new HashSet<Zahlung>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Parkhaus_Id { get; set; }
        public Nullable<int> AnzahlParkplaetze { get; set; }
    
        public virtual Parkhaus Parkhaus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dauermieter> Dauermieter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zahlung> Zahlung { get; set; }
    }
}
