//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkhausManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarif
    {
        public int Id { get; set; }
        public Nullable<bool> Typ { get; set; }
        public Nullable<System.TimeSpan> Von { get; set; }
        public Nullable<System.TimeSpan> Bis { get; set; }
        public Nullable<double> Preis { get; set; }
        public int Parkhaus_Id { get; set; }
    
        public virtual Parkhaus Parkhaus { get; set; }
    }
}
