//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkhausManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Zahlung = new HashSet<Zahlung>();
        }
    
        public int Id { get; set; }
        public int ParkplatzNummer { get; set; }
        public int Stockwerk_Id { get; set; }
        public Nullable<System.DateTime> Eintrittszeit { get; set; }
        public Nullable<bool> Bezahlt { get; set; }
        public Nullable<System.DateTime> BezahltZeit { get; set; }
        public Nullable<bool> Benutzt { get; set; }
    
        public virtual Stockwerk Stockwerk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zahlung> Zahlung { get; set; }
    }
}
